[2025-02-16T10:13:18.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T10:13:18.735+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobscraper_dag.transform_data manual__2025-02-16T10:11:49.421006+00:00 [queued]>
[2025-02-16T10:13:18.760+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobscraper_dag.transform_data manual__2025-02-16T10:11:49.421006+00:00 [queued]>
[2025-02-16T10:13:18.762+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-16T10:13:19.167+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_data> on 2025-02-16 10:11:49.421006+00:00
[2025-02-16T10:13:19.229+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=569) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T10:13:19.231+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'jobscraper_dag', 'transform_data', 'manual__2025-02-16T10:11:49.421006+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/jobscraper.py', '--cfg-path', '/tmp/tmpa_h4lcyk']
[2025-02-16T10:13:19.234+0000] {standard_task_runner.py:72} INFO - Started process 583 to run task
[2025-02-16T10:13:19.260+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask transform_data
[2025-02-16T10:13:19.564+0000] {task_command.py:467} INFO - Running <TaskInstance: jobscraper_dag.transform_data manual__2025-02-16T10:11:49.421006+00:00 [running]> on host 209597978c5a
[2025-02-16T10:13:19.919+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='mainguyen' AIRFLOW_CTX_DAG_ID='jobscraper_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T10:11:49.421006+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T10:11:49.421006+00:00'
[2025-02-16T10:13:19.923+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-16T10:13:19.924+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-16T10:13:19.926+0000] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2025-02-16 10:13:18.736326+00:00
[2025-02-16T10:13:19.929+0000] {logging_mixin.py:190} INFO - Dag name:jobscraper_dag and current dag run status:running
[2025-02-16T10:13:19.931+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T10:13:19.971+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/jobscraper.py", line 61, in transform_data
    df.to_csv("./data/job_list.csv", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data'
[2025-02-16T10:13:20.001+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-16T10:13:20.003+0000] {logging_mixin.py:190} INFO - Task start:2025-02-16 10:13:18.736326+00:00 end:2025-02-16 10:13:20.000849+00:00 duration:1.264523
[2025-02-16T10:13:20.004+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_data> dag:<DAG: jobscraper_dag> dagrun:<DagRun jobscraper_dag @ 2025-02-16 10:11:49.421006+00:00: manual__2025-02-16T10:11:49.421006+00:00, state:running, queued_at: 2025-02-16 10:11:49.493337+00:00. externally triggered: True>
[2025-02-16T10:13:20.005+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: 'data'
[2025-02-16T10:13:20.006+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=jobscraper_dag, task_id=transform_data, run_id=manual__2025-02-16T10:11:49.421006+00:00, execution_date=20250216T101149, start_date=20250216T101318, end_date=20250216T101320
[2025-02-16T10:13:20.063+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T10:13:20.065+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task transform_data (Cannot save file into a non-existent directory: 'data'; 583)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/jobscraper.py", line 61, in transform_data
    df.to_csv("./data/job_list.csv", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data'
[2025-02-16T10:13:20.112+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-16T10:13:20.151+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T10:13:20.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
